baseURL = "https://mrunalnshah.github.io/"
languageCode = "en-us"
title = "mrunalnshah"
theme="archie"
copyright = "© mrunalnshah"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[pagination]
  pagerSize = 3 # articles per page

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Welcome."
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/mrunalnshah/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/mrunalnshah/"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/mrunalnshah/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4