baseURL = "https://mrunalnshah.github.io/BlogVerse/"
relativeURLs = false
canonifyURLs = true

languageCode = "en-us"
title = "mrunalnshah"
theme="archie"
copyright = "© mrunalnshah"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[pagination]
  pagerSize = 3 # articles per page

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Welcome to BlogVerse."
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

# Social Tags
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/mrunalnshah/"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/mrunalnshah/"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:mrunalnshah2883@gmail.com"

# Main menu Items
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4